### ISSUE TITLE
Think about integaration

### ISSUE THREAD

**Issue by aalavandhan** [Codebrahma/factory_group#15]
How will developers use the GEM? It will make more sense if all the factory definitions are placed in one file, say `spec/factories/groups.rb`. If this is the case, a generator has to be built to generate this file with some basic examples as comments. Further this generator should also `require` this file in `spec_helper.rb` so that it's available in individual spec files.

What do you think @Charizard

**Comment by Charizard** [comment]
@nithinkrishna Yeah you are right, there needs to be a place where all the factories should go. It would be under `spec/factory_groups/`. However this folder needs to be required inside `spec_helper.rb`. Initially let's instruct the users to require it manually.

Hope that answers all your questions.
